substitutions:
  name: "rgbww-led-control-5a"
  friendly_name: "RGBWW LED Controller 5A"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2026.3.3
  name_add_mac_suffix: true
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: led_status
          effect: "Rainbow"

esp32:
  variant: ESP32C3
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/mikelawrence/esphome-components
    components: [rgbww_power_limited]

# API is a requirement of the dashboard import
# Grab a key from https://esphome.io/components/api.html
api:
#   encryption:
#     key:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    # password: !secret ota_password

# WiFi is required
wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   use_address: xxx.xxx.xxx.xxx

# Allows user to provision WiFi credentials with Bluetooth using Improv standard
esp32_improv:
  authorizer: none

# Allow user to provision WiFi credentials with USB port using Improv standard
improv_serial:

# Enable logging
logger:
  logs:
    pulse_counter: ERROR
    ads1115.sensor: ERROR
    ina2xx_i2c: ERROR

ads1115:
  address: 0x48
  continuous_mode: false

i2c:
  sda: GPIO1
  scl: GPIO8
  scan: true
  frequency: 400kHz

interval:
  - interval: 10s
    then:
      - output.turn_on: led_temp_ref_enable
      - delay: 10ms
      - component.update: t0_voltage
      - component.update: t1_voltage
      - component.update: t2_voltage
      - component.update: t3_voltage
      - output.turn_off: led_temp_ref_enable

time:
  - platform: homeassistant
    id: homeassistant_time

button:
  - platform: restart
    name: "Restart"

fan:
  - platform: speed
    output: fan_pwm
    name: "Fan"
    restore_mode: RESTORE_DEFAULT_ON

light:
  - platform: esp32_rmt_led_strip
    id: led_status
    rgb_order: RGB
    pin: GPIO2
    num_leds: 1
    chipset: ws2812
    effects:
      - addressable_rainbow:
          name: Rainbow
          speed: 10
          width: 50
  - platform: rgbww_power_limited
    id: rgbww_light_1
    name: "Light"
    red: output_red_int
    green: output_green_int
    blue: output_blue_int
    cold_white: output_cw_int
    warm_white: output_ww_int
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2800 K
    constant_brightness: false
    color_interlock: false
    restore_mode: RESTORE_DEFAULT_OFF
    max_power: 0.7 # Cap at 70% of total system power

output:
  - platform: gpio
    pin: GPIO7
    id: led_temp_ref_enable
  - platform: template
    id: output_red_int
    type: float
    write_action:
      - lambda: !lambda |-
          id(output_red).set_level(state);
          id(red).publish_state(state * 100.0f);
  - platform: template
    id: output_green_int
    type: float
    write_action:
      - lambda: !lambda |-
          id(output_green).set_level(state);
          id(green).publish_state(state * 100.0f);
  - platform: template
    id: output_blue_int
    type: float
    write_action:
      - lambda: !lambda |-
          id(output_blue).set_level(state);
          id(blue).publish_state(state * 100.0f);
  - platform: template
    id: output_ww_int
    type: float
    write_action:
      - lambda: !lambda |-
          id(output_ww).set_level(state);
          id(ww).publish_state(state * 100.0f);
  - platform: template
    id: output_cw_int
    type: float
    write_action:
      - lambda: !lambda |-
          id(output_cw).set_level(state);
          id(cw).publish_state(state * 100.0f);
  - platform: ledc
    pin: GPIO20
    id: fan_pwm
    frequency: 1000Hz # Standard for 4-pin PWM fans
  - platform: ledc
    pin: GPIO4
    id: output_red
    frequency: 1000Hz
    phase_angle: 0
  - platform: ledc
    pin: GPIO10
    id: output_green
    frequency: 1000Hz
    phase_angle: 20
  - platform: ledc
    pin: GPIO5
    id: output_blue
    frequency: 1000Hz
    phase_angle: 40
  - platform: ledc
    pin: GPIO6
    id: output_ww
    frequency: 1000Hz
    phase_angle: 60
  - platform: ledc
    pin: GPIO3
    id: output_cw
    frequency: 1000Hz
    phase_angle: 80

sensor:
  - platform: pulse_counter
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    name: "Fan RPM"
    unit_of_measurement: "RPM"
    icon: "mdi:fan"
    accuracy_decimals: 0
    update_interval: 1s
    filters:
      - multiply: 0.5
      - or:
          - throttle: 60s
          - delta: 50
  # This sensor includes everything on this board
  - platform: ina2xx_i2c
    id: usb_c_power_sensor
    model: INA238
    shunt_resistance: 0.008ohm
    max_current: 10A
    adc_range: 0 # ±163.84 mV
    update_interval: 60s
    reset_on_boot: false
    bus_voltage:
      name: "Voltage"
      accuracy_decimals: 2
    power:
      name: "Power"
      accuracy_decimals: 2
    current:
      name: "Current"
      accuracy_decimals: 3
  - platform: sht3xd
    address: 0x44
    update_interval: 60s
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
  - platform: ads1115
    id: t0_voltage
    multiplexer: "A0_GND"
    gain: 2.048
    update_interval: never
    filters:
      - filter_out: 2.047
  - platform: ads1115
    id: t1_voltage
    multiplexer: "A1_GND"
    gain: 2.048
    update_interval: never
    filters:
      - filter_out: 2.047
  - platform: ads1115
    id: t2_voltage
    multiplexer: "A2_GND"
    gain: 2.048
    update_interval: never
    filters:
      - filter_out: 2.047
  - platform: ads1115
    id: t3_voltage
    multiplexer: "A3_GND"
    gain: 2.048
    update_interval: never
    filters:
      - filter_out: 2.047
  - platform: resistance
    id: t0_resistance
    sensor: t0_voltage
    configuration: DOWNSTREAM
    resistor: 61.9kOhm
  - platform: resistance
    id: t1_resistance
    sensor: t1_voltage
    configuration: DOWNSTREAM
    resistor: 61.9kOhm
  - platform: resistance
    id: t2_resistance
    sensor: t2_voltage
    configuration: DOWNSTREAM
    resistor: 61.9kOhm
  - platform: resistance
    id: t3_resistance
    sensor: t3_voltage
    configuration: DOWNSTREAM
    resistor: 61.9kOhm
  - platform: ntc
    name: "LED Strip 1 Temperature"
    sensor: t0_resistance
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - or:
          - throttle: 60s
          - delta: 1
  - platform: ntc
    name: "LED Strip 2 Temperature"
    sensor: t1_resistance
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - or:
          - throttle: 60s
          - delta: 1
  - platform: ntc
    name: "LED Strip 3 Temperature"
    sensor: t2_resistance
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - or:
          - throttle: 60s
          - delta: 1
  - platform: ntc
    name: "LED Strip 4 Temperature"
    sensor: t3_resistance
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - or:
          - throttle: 60s
          - delta: 1
  - platform: template
    name: "LED Red"
    id: red
    update_interval: never
    accuracy_decimals: 1
    unit_of_measurement: "%"
    disabled_by_default: true
    filters:
      - throttle: 1s
  - platform: template
    name: "LED Green"
    id: green
    update_interval: never
    accuracy_decimals: 1
    unit_of_measurement: "%"
    disabled_by_default: true
    filters:
      - throttle: 1s
  - platform: template
    name: "LED Blue"
    id: blue
    update_interval: never
    accuracy_decimals: 1
    unit_of_measurement: "%"
    disabled_by_default: true
    filters:
      - throttle: 1s
  - platform: template
    name: "LED White Warm"
    id: ww
    update_interval: never
    accuracy_decimals: 1
    unit_of_measurement: "%"
    disabled_by_default: true
    filters:
      - throttle: 1s
  - platform: template
    name: "LED White Cool"
    id: cw
    update_interval: never
    accuracy_decimals: 1
    unit_of_measurement: "%"
    disabled_by_default: true
    filters:
      - throttle: 1s
