name: Publish Firmware

on:
  workflow_run:
    workflows:
      - Create Pre-Release
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-release-info:
    name: Get Release Info
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: get-latest-release
        uses: cardinalby/git-get-release-action@1.2.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
          prerelease: true

    outputs:
      summary: ${{ steps.get-latest-release.outputs.body }}
      url: ${{ steps.get-latest-release.outputs.html_url }}
      version: ${{ steps.get-latest-release.outputs.tag_name }}

  build-firmware:
    name: Build Firmware
    needs: get-release-info
    uses: esphome/workflows/.github/workflows/build.yml@2025.10.0
    with:
      files: |
        rgbww-led-controller-5a.factory.yaml
        rgbww-led-controller-10a.factory.yaml
      esphome-version: latest
      release-summary: ${{ needs.get-release-info.outputs.summary }}
      release-url: ${{ needs.get-release-info.outputs.url }}
      release-version: ${{ needs.get-release-info.outputs.version }}

  rewind-pre-release:
    name: Rewind Pre-Release on Build FirmwareFailure
    needs: build-firmware
    runs-on: ubuntu-latest
    if: failure()
    permissions:
      contents: write
    steps:
      - name: Delete Tag and Release
        run: gh release delete "$TAG" --cleanup-tag --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.build-firmware.outputs.version }}

  upload-firmware:
    name: Upload Firmware
    needs: build-firmware
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2025.10.0
    with:
      version: ${{ needs.build-firmware.outputs.version }}

  promote-pre-release:
    name: Promote Pre-Release to Release
    needs: 
      - build-firmware
      - upload-firmware
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Promote Pre-Release to Release
        run: gh release edit "$TAG" --prerelease=false --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.build-firmware.outputs.version }}
