name: Publish Firmware

on:
  workflow_run:
    workflows:
      - Create Release
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-release-info:
    name: Get Release Info
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: get-latest-release
        uses: cardinalby/git-get-release-action@1.2.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
          prerelease: true

    outputs:
      summary: ${{ steps.get-latest-release.outputs.body }}
      url: ${{ steps.get-latest-release.outputs.html_url }}
      version: ${{ steps.get-latest-release.outputs.tag_name }}

  build-firmware:
    name: Build Firmware
    needs: get-release-info
    uses: esphome/workflows/.github/workflows/build.yml@2026.4.0
    with:
      files: |
        rgbww-led-controller-5a.factory.yaml
        rgbww-led-controller-10a.factory.yaml
      esphome-version: latest
      release-summary: ${{ needs.get-release-info.outputs.summary }}
      release-url: ${{ needs.get-release-info.outputs.url }}
      release-version: ${{ needs.get-release-info.outputs.version }}

  rewind-pre-release:
    name: Rewind Pre-Release on Build Firmware Failure
    needs: build-firmware
    runs-on: ubuntu-latest
    if: failure()
    permissions:
      contents: write

    steps:
      - uses: ClementTsang/delete-tag-and-release@v0.4.0
        with:
          delete_release: true
          tag_name: ${{ needs.build-firmware.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-firmware:
    name: Upload Firmware
    needs: build-firmware
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2026.4.0
    with:
      version: ${{ needs.build-firmware.outputs.version }}

  promote-pre-release:
    name: Promote Pre-Release to Release
    needs:
      - build-firmware
      - upload-firmware
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Release ID
        id: get_release
        uses: joutvhu/get-release@v1
        with:
          tag_name: ${{ needs.build-firmware.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Promote Pre-Release to Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ steps.get_release.outputs.id }}
          prerelease: false
