name: YAML lint

on:
  pull_request:
    paths:
      - "**.yaml"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  yamllint:
    name: 🧹 yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1.5.0
        with:
          strict: true
